/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sep.ui;

import com.sep.Client;
import com.sep.Event;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.FormatterClosedException;
import java.util.List;
import java.util.NoSuchElementException;
import java.util.Scanner;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ema
 */
public class SeniorCustomerService extends javax.swing.JFrame {

    /**
     * Creates new form SeniorCustomerService
     */
    public SeniorCustomerService() {
        initComponents();
        setLocationRelativeTo(null);
    }

    public void setLabelUser(String s) {
        lblUser.setText(s);
    }
    private Scanner scan;

    public void openFile() {
        try {

            scan = new Scanner(new File("events.txt"));
        } catch (SecurityException securityException) {
            JOptionPane.showMessageDialog(null, "You do not have write access to this file.");
            System.exit(1); // terminate the program
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Exception caught: " + ex);
        }

    }

    public void readRecords() {

        Event event = new Event();
        Client cl = new Client();
        try {
            while (scan.hasNext()) {
                cl.setFirstName(scan.next());
                cl.setId(scan.nextInt());
                event.setEventType(scan.next());
                event.setFrom(scan.next());
                event.setTo(scan.next());
                event.setAtendee(scan.nextInt());
                List<String> pre = new ArrayList<>();
                String s;
                for (int i = 1; i < 3; ++i) {
                    if (scan.hasNext()) {
                        s = scan.next();
                        pre.add(s);
                        event.setPreference((ArrayList) pre);
                        //JOptionPane.showMessageDialog(null, s);
                    } else {
                        break;
                    }
                }
                event.setBudget(scan.nextDouble());

                System.out.printf("%s %d %s %s %s %d %s %.2f\n", cl.getFirstName(), cl.getId(), event.getEventType(),
                        event.getFrom(), event.getTo(), event.getAtendee(), event.getPreference(), event.getBudget());
            }
        } catch (FormatterClosedException formatterClosedException) {
            JOptionPane.showMessageDialog(null, "Error writing to file.");
        } catch (NoSuchElementException elementException) {
            JOptionPane.showMessageDialog(null, "Invalid input. Please try again.");
        }
    }

    public void closeFile() {
        if (scan != null) {
            scan.close();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setText("Welcome: ");

        lblUser.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblUser, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addComponent(lblUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );

        jButton1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButton1.setText("View Available Requests");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        RequestedEvents re = new RequestedEvents();
        Event event = new Event();
        openFile();
        Client cl = new Client();
        try {
            while (scan.hasNext()) {
                cl.setFirstName(scan.next());
                cl.setId(scan.nextInt());
                event.setEventType(scan.next());
                event.setFrom(scan.next());
                event.setTo(scan.next());
                event.setAtendee(scan.nextInt());
                List<String> pre = new ArrayList<>();
                String s;
                for (int i = 1; i <= 6; ++i) {
                    s = scan.next();
                    if (s.equals("end")) {
                        break;
                    } else { 
                        pre.add(s);
                        event.setPreference((ArrayList) pre);
                    }
                }
                event.setBudget(scan.nextDouble());

                List<String> p = new ArrayList<>();
                p = event.getPreference();
                String str = String.join(" ", p);
                DefaultTableModel model = (DefaultTableModel) re.getTblView().getModel();
                model.addRow(new Object[]{cl.getId(), cl.getFirstName(), event.getEventType(),
                    event.getFrom(), event.getTo(), event.getAtendee(), event.getBudget(), str});
            }
        } catch (FormatterClosedException formatterClosedException) {
            JOptionPane.showMessageDialog(null, "Error writing to file.");
        } catch (NoSuchElementException elementException) {
            JOptionPane.showMessageDialog(null, "Invalid input. Please try again.");
        }
        closeFile();
        re.setVisible(true);


    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeniorCustomerService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeniorCustomerService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeniorCustomerService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeniorCustomerService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SeniorCustomerService().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblUser;
    // End of variables declaration//GEN-END:variables
}
